name: Java CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Find JAR File
        id: find_jar
        run: |
          echo "Searching for JAR file..."
          JAR_FILE=$(find $GITHUB_WORKSPACE/target -name '*.jar')
          echo "JAR_FILE=${JAR_FILE}" >> $GITHUB_ENV

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: "./"
          target: "/home/ubuntu/pro/springboot"
      
      - name: Setup new version on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo systemctl restart springboot.service
            sudo systemctl restart nginx
